# Generated by Marten 0.3.0 on 2023-07-07 12:41:19 -04:00

class Migration::Profiles::V202307071241191 < Marten::Migration
  depends_on :auth, "0001_create_auth_user_table"
  depends_on :blogging, "202307071241191_auto"

  def plan
    create_table :profiles_profile do
      column :id, :big_int, primary_key: true, auto: true
      column :username, :string, max_size: 128, unique: true
      column :bio, :text, null: true
      column :image_url, :string, max_size: 200, null: true
      column :user_id, :reference, to_table: :auth_user, to_column: :id, unique: true
    end

    create_table :profiles_profile_followed_users do
      column :id, :big_int, primary_key: true, auto: true
      column :self_id, :reference, to_table: :profiles_profile_followed_users, to_column: :id
      column :profile_id, :reference, to_table: :profiles_profile, to_column: :id
    end

    create_table :profiles_profile_favorite_articles do
      column :id, :big_int, primary_key: true, auto: true
      column :profile_id, :reference, to_table: :profiles_profile, to_column: :id
      column :article_id, :reference, to_table: :blogging_article, to_column: :id
    end
  end
end
