# Generated by Marten 0.3.1 on 2023-07-21 21:59:48 -04:00

class Migration::Profiles::V202307212159481 < Marten::Migration
  depends_on :profiles, "202307071241191_auto"

  def plan
    rename_column :profiles_profile_followed_users, :profile_id, :from_profile_id

    remove_column :profiles_profile_followed_users, :self_id

    add_column :profiles_profile_followed_users, :to_profile_id, :reference, to_table: :profiles_profile, to_column: :id
  end
end
