# Generated by Marten 0.3.0 on 2023-07-07 12:41:19 -04:00

class Migration::Blogging::V202307071241191 < Marten::Migration
  def plan
    create_table :blogging_tag do
      column :id, :big_int, primary_key: true, auto: true
      column :label, :string, max_size: 255
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :blogging_comment do
      column :id, :big_int, primary_key: true, auto: true
      column :body, :text
      column :created_at, :date_time
      column :updated_at, :date_time
    end

    create_table :blogging_article_tags do
      column :id, :big_int, primary_key: true, auto: true
    end

    create_table :blogging_article do
      column :id, :big_int, primary_key: true, auto: true
      column :title, :string, max_size: 255
      column :description, :text
      column :body, :text
      column :created_at, :date_time
      column :updated_at, :date_time
    end
  end
end
