# Generated by Marten 0.3.2 on 2023-08-13 11:57:21 -04:00

class Migration::Blogging::V202308131157211 < Marten::Migration
  depends_on :blogging, "202307071241192_auto"

  def plan
    add_column :blogging_article, :slug, :string, max_size: 50, index: true
  end
end
