# Generated by Marten 0.3.0 on 2023-07-07 12:41:19 -04:00

class Migration::Blogging::V202307071241192 < Marten::Migration
  depends_on :profiles, "202307071241191_auto"
  depends_on :blogging, "202307071241191_auto"

  def plan
    add_column :blogging_article, :author_id, :reference, to_table: :profiles_profile, to_column: :id

    add_column :blogging_article_tags, :article_id, :reference, to_table: :blogging_article, to_column: :id

    add_column :blogging_article_tags, :tag_id, :reference, to_table: :blogging_tag, to_column: :id

    add_column :blogging_comment, :article_id, :reference, to_table: :blogging_article, to_column: :id

    add_column :blogging_comment, :author_id, :reference, to_table: :profiles_profile, to_column: :id
  end
end
