name: QA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"

jobs:
  qa:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.18.1
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          apt-get update
          apt-get -yqq install cmake build-essential
      - name: Install shards
        run: |
          git config --global --add safe.directory /__w/realworld/realworld
          git config --global --add safe.directory /__w/realworld/realworld/shard_overrides/marten
          git submodule init
          git submodule update --remote --recursive
          shards install --ignore-crystal-version
      - name: Run QA checks
        run: make qa_crystal
